refactor(scripting): remove set -e

diff --git a/bash-scripting/basics b/bash-scripting/basics
--- a/bash-scripting/basics
+++ b/bash-scripting/basics
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -e #? exit script if any command fails
+set -e #? exit script if any command fails #! not recommended
 
 some_var=$(ls)   #? sub shells
 echo "$some_var" #? always surround them with ""
